### ISSUE TITLE
OBD record sometimes runs at 100% cpu in the background after disconnect

### ISSUE THREAD

**Issue by rpfile** [obdgeek/obd-record#10]
i recorded two trips this morning, then while sitting in the car, pressed disconnect. left OBD record in the background.

the iphone eventually got very hot and stopped charging. looking at the battery tab, OBD record was using 98% of the battery usage and is logging 1h of activity every 1h, so must be at 100% CPU.

**Comment by obdgeek** [comment]
Power is slowly being addressed and I’ve marked a number of areas ripe for improvement. Also when not connected to a scan tool there are still some threads that aren’t being killed that are a work in progress. I would recommend OBD Record be removed from memory when not in use.

The build I’m testing now disables location data except when it is needed (during a trip and at the beginning of a charge). I just saw in the Apple documentation that they recommend the device be plugged in when an application is using navigation-grade location data but I never do it.

**Comment by rpfile** [comment]
ok great, maybe it is the location thing, who knows. will test again in the new build when it arrives.

**Comment by obdgeek** [comment]
I don't know how much I can help with the active power use since this is a navigation app on steroids.  Not only is precise location data being collected it has the extra overhead of the Bluetooth comms collecting vehicle data from the scan tool and then pushing the data to the cloud.

But I will make sure when you are not actively traveling or charging it will have a small power budget.

**Comment by rpfile** [comment]
i guess by the "location thing" i meant checking the location repeatedly while not connected. but if the location polling was the sole cause of the problem, it would happen during normal use and again i didn't see that kind of battery drain while recording trips. i assume google maps and apple maps are polling as frequently as you are and they also don't result in overheating. i think there is some kind of bug where the app eventually ends up in an infinite loop when it's backgrounded and disconnected.

**Comment by obdgeek** [comment]
I know there are threads that aren't being killed when you disconnect from the scan tool.  Just have to complete the rework of the scan tool command and response queues to make sure hey are created and killed off properly.
