### ISSUE TITLE
DB settings are sometimes immutable

### ISSUE THREAD

**Issue by rpfile** [obdgeek/obd-record#5]
i set up a database on influxdb and entered the info into OBD Record. i fat fingered the URL and had also used the wrong API token. when i tried to change these in the OBD Record UI, the changes "worked" in that when i pressed the "test" button the app was happy, but i didn't click "update" (didn't notice it there) but instead just went "back". eventually i restarted OBD record and was surprised to see my URL typo and wrong API key there. i did eventually find the "update" button and clicked it and the changes seem to have stuck.

i'm not sure this conforms to iOS UI standards. usually when you back out of a screen any changes are applied. but if you don't want to do it like this, maybe there should be "save" and "cancel" buttons at the bottom of the DB entry screen, where "save" commits the changes and "cancel" takes you back to the previous screen.

over in OBD Play, the same thing happened (accidentally entered the bad data from OBD Record by copy/paste). i eventually realized the URL and API key were wrong and tried to fix them. however, no matter how many times i clicked "update", the URL and API key would not save properly. i had to create a new connection with the corrected URL/API key and delete the old one.

**Comment by obdgeek** [comment]
I don't disagree, perhaps 'Cancel' in place of 'Update' and back makes any changes stick.  Of just a dialog asking if you want any changes saved would work.

Thanks for the input.
