### ISSUE TITLE
OBD Record does not consistently transition to trip recording (v 0.50 (5))

### ISSUE THREAD

**Issue by rpfile** [obdgeek/obd-record#6]
this one i can't provide a list of steps to reproduce. all i know is that OBD Record only transitioned to the "trip" state once while i was using it. most of the time it was 'stuck' in the Connected state and sat there throughout an actual trip. it also sometimes showed the ignition state as "off" when it was on, which might be related.

**Comment by obdgeek** [comment]
There are known issues with state transitions that are being worked on, in particular if you walk away and it disconnects then you return it will show Connected but will not recognize the ignition being on (which should be noted in the TestFlight release notes).

If the vehicle is on and you are not in the 'Ignition On' state then you need to relaunch OBD Record in which case it works reliably for me in build 0.50.5. More rarely I might need to disconnect the scan tool in the device Bluetooth settings along with relaunching OBD Record.

**Comment by rpfile** [comment]
hmm. i just tried restarting OBD Record while the ignition was on (and it was showing ignition off), and it did not resolve.
the only thing that helped was rebooting my phone and then starting OBD Record again. then it worked fine and i recorded two trips with no problem. i don't know how to get it back into the broken state.

is there a background process that does not get killed when the user swipes-to-close the OBD Record application?

when it was giving me trouble, i didn't walk away from the car for sure, i was sitting in it the whole time.

**Comment by obdgeek** [comment]
> hmm. i just tried restarting OBD Record while the ignition was on (and it was showing ignition off), and it did not resolve.
the only thing that helped was rebooting my phone and then starting OBD Record again. then it worked fine and i recorded two trips with no problem. i don't know how to get it back into the broken state.

I have never rebooted a device, swipe up to remove and restart and perhaps disconnect the scan tool in the Settings but not a reboot.

> is there a background process that does not get killed when the user swipes-to-close the OBD Record application?

No

**Comment by rpfile** [comment]
> I have never rebooted a device, swipe up to remove and restart and perhaps disconnect the scan tool in the Settings but not a reboot.
> 

i did try those things, and it did not resolve the problem. i don't know what to say other than rebooting my phone caused OBD Record to start behaving properly. again i don't know how it got into this state so unless it spontaneously happens again, i can't say more about it.

hopefully whatever state transition fixes you have coming will address this problem.
